---
title: "Informe"
author: "Javier Savedra - Thomas Gonzalez"
date: "2024-03-01"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      warning = FALSE,
                      message = FALSE)
```


```{r}
rm(list=ls())
#load("Aplicacion_thomas_javier_log_iga.RData")
load("~/tesis_R/Aplicacion_thomas_javier_log_iga.RData")
library(ggplot2)
library(gridExtra)
library(gamlss)

dados <- datos
y <- y_


v1 <- ggplot(dados, aes(x = y_)) +  # Agrega aes() alrededor de y_
  geom_histogram(bins = 9, aes(y = ..density..), fill = "steelblue") +
  theme(
    axis.text.x = element_text(size = 16, face = "plain"),
    axis.text.y = element_text(size = 16, face = "plain"),
    axis.title.x = element_text(size = 20, face = "plain"),
    axis.title.y = element_text(size = 20, face = "plain")
  ) +
  stat_function(
    fun = dNO,
    args = list(mu = mean(y_), sigma = sd(y_)),  # Utiliza y_ en lugar de y
    col = "black",
    size = 1
  ) +
  xlim(6,16) +
  xlab("Log IGA")


v1

v2 <- ggplot(dados, aes(x2, y_)) +
  geom_boxplot(fill = "steelblue") +
  theme(
    axis.text.x = element_text(size = 16, face = "plain"),
    axis.text.y = element_text(size = 16, face = "plain"),  
    axis.title.x = element_text(size = 20, face = "plain"),
    axis.title.y = element_text(size = 20, face = "plain")
  )+
  xlab("Categoria Vacuna")

# Grafico suavizado para IMC (v3)
v3 <- ggplot(dados, aes(x1, y_)) +
  geom_point(size = 3) +
  geom_smooth(se = FALSE, method = "loess", col = "red", size = 2) + 
  theme(
    axis.text.x = element_text(size = 16, face = "plain"),
    axis.text.y = element_text(size = 16, face = "plain"),  
    axis.title.x = element_text(size = 20, face = "plain"),
    axis.title.y = element_text(size = 20, face = "plain")
  ) +
  xlab("IMC")

# Grafico suavizado para Log Neutra (v4)
v4 <- ggplot(dados, aes(x3, y_)) +
  geom_point(size = 3) +
  geom_smooth(se = FALSE, method = "loess", col = "red", size = 2) + 
  theme(
    axis.text.x = element_text(size = 16, face = "plain"),
    axis.text.y = element_text(size = 16, face = "plain"),  
    axis.title.x = element_text(size = 20, face = "plain"),
    axis.title.y = element_text(size = 20, face = "plain")
  ) +
  xlab("Log Neutra")

# Grafico suavizado para Edad (v5)
v5 <- ggplot(dados, aes(x4, y_)) +
  geom_point(size = 3) +
  geom_smooth(se = FALSE, method = "loess", col = "red", size = 2) +
  theme(
    axis.text.x = element_text(size = 16, face = "plain"),
    axis.text.y = element_text(size = 16, face = "plain"),  
    axis.title.x = element_text(size = 20, face = "plain"),
    axis.title.y = element_text(size = 20, face = "plain")
  ) +
  xlab("Edad")
v6 <- ggplot(dados, aes(x5, y_)) +
  geom_boxplot(fill = "steelblue") +
  theme(
    axis.text.x = element_text(size = 16, face = "plain"),
    axis.text.y = element_text(size = 16, face = "plain"),  
    axis.title.x = element_text(size = 20, face = "plain"),
    axis.title.y = element_text(size = 20, face = "plain")
  )+
  xlab("Sexo")

grid.arrange(v2, v3, v5, v4)

v6

# Calcular la matriz de correlación
correlation_matrix_log_iga <- cor(dados1[, c("log_iga", "imc", "edad", "log_neutra")])

# Convertir la matriz de correlación en un dataframe
correlation_df <- as.data.frame(correlation_matrix_log_iga)
correlation_df$variable1 <- rownames(correlation_matrix_log_iga)
correlation_df <- tidyr::gather(correlation_df, variable2, value, -variable1)

# Crear un gráfico de heatmap para la matriz de correlación
heatmap_plot_log_iga <- ggplot(data = correlation_df, aes(variable1, variable2, fill = value)) +
  geom_tile(color = "white") +
  scale_fill_gradient2(low = "blue", high = "red", mid = "white", midpoint = 0, limit = c(-1,1), space = "Lab", name="Correlation") +
  theme_minimal() +
  theme(axis.text.x = element_text(size = 16, face = "plain"),
        axis.text.y = element_text(size = 16, face = "plain"),
        axis.title.x = element_text(size = 20, face = "plain"),
        axis.title.y = element_text(size = 20, face = "plain")) +
  labs(x = "Variables", y = "Variables", title = "Matriz de Correlación (log Iga vs. x1, x3, x4)")


heatmap_plot_log_iga



GAIC(Normal_identidade,
     tStudent_identidade,
     Exponencial_potencia_identidade,
     Normal_inversa,
     tStudent_inversa,
     Exponencial_potencia_inversa,
     Normal_log,
     tStudent_log,
     Exponencial_potencia_log,
     Normal_sqrt,
     tStudent_sqrt,
     Exponencial_potencia_sqrt)

wp(tStudent_inversa,ylim.all = 3)

summary(tStudent_sqrt)

exp(tStudent_inversa$nu.coefficients)

#x11()
term.plot(tStudent_inversa, 
          what = c("mu"),
          terms = 4,main="",
          col.shaded="royalblue",
          col.term = "gray83",
          xlabs="temperature",col.se="black",
          ylabs="Partial for cs(temperature)",
          lwd.term = 4,
          lwd.se=2,
          lty.se = 1)
#____________________________________________________________________
#Tendencias y vs x's 

#y vs x2
#x11()
plot(x4,y_,pch=19,main="",col="royalblue4",
     xlab="Measured height",
     ylab="Measured weight")
lines(smooth.spline(x4,fitted(tStudent_inversa)),
     type="l",col="red",lwd=4)


#____________________________________________________________
#           Qualidade de ajuste da dist. t-Student,
#justificativa para dizer que a dist. t-Student n?o 
#ajustou-se bem aos dados


plot(Res.q2,pch=1,col="red2",lwd=4,
     ylab="Quantile residuals",xlab="Index",
     main ="",ylim = c(-5,5),cex.lab=1.2)
abline(h=-3,lwd=4,lty=2,col="1")
abline(h=0,lwd=2,lty=1,col="4")
abline(h=3,lwd=4,lty=2,col="1")
#identify(index,Res.q2)


qqnorm(Res.qo,pch=19,col="red2",
       xlim=c(-3,3),
       ylim=c(-4,4),
       ylab="Quantile residuals",
       xlab="N(0,1) quantiles",main = "",cex.lab=1.2)
lines(Z,rqmax,col="1",lwd=3)
lines(Z,rqm , lty = 2,col="4",lwd=3)
lines(Z,rqmin,col="1",lwd=3)
legend("topleft", c(paste("Total points:", n),
       paste("Points out of envelope:",
       res.out , "(", per.out, "%)")),
       bty="n", cex=1.2)


```

